from sqlalchemy.types import NUMERIC, SMALLINT, INTEGER, VARCHAR, Boolean, TEXT, TIMESTAMP

TABLE_SCHEMA = {
    # 'tbl_buu_cuc_best': {
    #     'receiver_province': VARCHAR(length=30),
    #     'receiver_district': VARCHAR(length=30),
    #     'n_post_offices': SMALLINT,
    #     "import_time": TIMESTAMP,
    # },
    # 'tbl_buu_cuc_ghn': {
    #     'receiver_province': VARCHAR(length=30),
    #     'receiver_district': VARCHAR(length=30),
    #     'n_post_offices': SMALLINT,
    #     "import_time": TIMESTAMP,
    # },
    # 'tbl_buu_cuc_ghtk': {
    #     'receiver_province': VARCHAR(length=30),
    #     'receiver_district': VARCHAR(length=30),
    #     'n_post_offices': SMALLINT,
    #     "import_time": TIMESTAMP,
    # },
    # 'tbl_buu_cuc_ninja_van': {
    #     'receiver_province': VARCHAR(length=30),
    #     'receiver_district': VARCHAR(length=30),
    #     'n_post_offices': SMALLINT,
    #     "import_time": TIMESTAMP,
    # },
    'tbl_buu_cuc': {
        'receiver_province': VARCHAR(length=30),
        'receiver_district': VARCHAR(length=30),
        'carrier': VARCHAR(length=30),
        'status': VARCHAR(length=500),
        'score': SMALLINT,
        'criteria': VARCHAR(length=50),
        'criteria_weight': SMALLINT,
        "import_time": TIMESTAMP,
    },
    # 'tbl_clnb_ninja_van': {
    #     'receiver_province': VARCHAR(length=30),
    #     'receiver_district': VARCHAR(length=30),
    #     "njv_post_office": VARCHAR(length=100),
    #     "delivery_success_rate": NUMERIC(3, 2),
    #     "is_more_than_100": Boolean,
    #     "import_time": TIMESTAMP,
    # },
    'tbl_clnb_ninja_van': {
        'receiver_province': VARCHAR(length=30),
        'receiver_district': VARCHAR(length=30),
        'carrier': VARCHAR(length=30),
        'status': VARCHAR(length=500),
        'score': SMALLINT,
        'criteria': VARCHAR(length=50),
        'criteria_weight': SMALLINT,
        "import_time": TIMESTAMP,
    },
    'tbl_ngung_giao_nhan': {
        'sender_province_code': VARCHAR(length=2),
        'sender_district_code': VARCHAR(length=3),
        'receiver_province_code': VARCHAR(length=2),
        'receiver_district_code': VARCHAR(length=3),
        'carrier_id': SMALLINT,
        'status': VARCHAR(length=30),
        "import_time": TIMESTAMP,
    },
    'tbl_ngung_giao_nhan_level_3': {
        'receiver_province_code': VARCHAR(length=2),
        'receiver_district_code': VARCHAR(length=3),
        'receiver_commune_code': VARCHAR(length=5),
        'carrier_id': SMALLINT,
        'status': VARCHAR(length=30),
        "import_time": TIMESTAMP,
    },
    'tbl_phan_vung_nvc': {
        "carrier": VARCHAR(length=20),
        "receiver_province": VARCHAR(length=30),
        "receiver_district": VARCHAR(length=30),
        "outer_region": VARCHAR(length=30),
        "inner_region": VARCHAR(length=30),
        "import_time": TIMESTAMP,
    },
    'tbl_order_type': {
        'carrier_id': SMALLINT,
        'sender_province_code': VARCHAR(length=2),
        'sender_district_code': VARCHAR(length=3),
        'receiver_province_code': VARCHAR(length=2),
        'receiver_district_code': VARCHAR(length=3),
        'order_type': VARCHAR(length=50),
        'new_type': VARCHAR(length=2),
        'route_type': VARCHAR(length=1),
    },
    'tbl_service_fee': {
        'carrier_id': SMALLINT,
        'order_type': VARCHAR(length=50),
        'new_type': VARCHAR(length=2),
        'pickup': VARCHAR(length=1),
        'weight': INTEGER,
        'service_fee': INTEGER,
    },
    'tbl_data_api': {
        'receiver_province_code': VARCHAR(length=2),
        'receiver_district_code': VARCHAR(length=3),
        'carrier_id': SMALLINT,
        'new_type': VARCHAR(length=2),
        'route_type': VARCHAR(length=1),
        'status': VARCHAR(length=1),
        'description': VARCHAR(length=500),
        'time_data': NUMERIC(5, 2),
        'time_display': VARCHAR(length=30),
        'speed_ranking': SMALLINT,
        'score_ranking': SMALLINT,
        'for_shop': SMALLINT,
        "total_order": SMALLINT,
        'rate_ranking': SMALLINT,
        'rate': NUMERIC(5, 2),
        "score": NUMERIC(3, 2),
        "star": NUMERIC(2, 1),
        "import_date": VARCHAR(length=10),
    },
    'tbl_optimal_score': {
        'date': VARCHAR(length=10),
        'score': NUMERIC(4, 3)
    },
    'tbl_data_visualization': {
        'order_code': VARCHAR(length=30),
        'sender_province_code': VARCHAR(length=2),
        "sender_province": VARCHAR(length=30),
        'sender_district_code': VARCHAR(length=3),
        "sender_district": VARCHAR(length=30),
        'receiver_province_code': VARCHAR(length=2),
        "receiver_province": VARCHAR(length=30),
        'receiver_district_code': VARCHAR(length=3),
        "receiver_district": VARCHAR(length=30),
        'carrier_id': SMALLINT,
        "carrier": VARCHAR(length=20),
        "order_type": VARCHAR(length=30),
        'new_type': VARCHAR(length=2),
        'route_type': VARCHAR(length=1),
        "weight": INTEGER,
        'price': INTEGER,
        'pickup_type': VARCHAR(length=30),
        'status': VARCHAR(length=1),
        'description': VARCHAR(length=500),
        'time_data': NUMERIC(5, 2),
        'time_display': VARCHAR(length=30),
        'total_order': INTEGER,
        'rate': NUMERIC(5, 2),
        'rate_ranking': SMALLINT,
        'for_shop': SMALLINT,
        'for_partner': SMALLINT,
        "score": NUMERIC(3, 2),
        "star": NUMERIC(2, 1),
        'price_ranking': SMALLINT,
        'speed_ranking': SMALLINT,
        'score_ranking': SMALLINT,
        "import_date": VARCHAR(length=10),
    },
}
