cookie:
  expiry_seconds: 2*24*60*60
  key: keys123456
  name: streamlit_cookie_name
credentials:
  names:
    trinh:
      email: emperorfire52@gmail.com
      username: superai_supership
      password: Trinh@SuperShip#24
preauthorized:
  emails:
    - emperorfire5252@gmail.com
