cookie:
  expiry_days: 2
  key: keys123456789
  name: streamlit_cookie_name_test
credentials:
  names:
    test:
      email: test@supership.com
      password: superai_test
      username: superai_test
preauthorized:
  emails:
  - test@supership.com
