cookie:
  expiry_days: 2
  key: keys123456
  name: streamlit_cookie_name
credentials:
  names:
    thao:
      email: thao52@gmail.com
      password: '123'
      username: thao
    trinh:
      email: emperorfire52@gmail.com
      password: Trinh@SuperShip#24
      username: superai_supership
preauthorized:
  emails:
  - emperorfire5252@gmail.com
